version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: lawyer.data.mssql
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=laywer.data.mssql.data001
        
    ports:
      - "1433:1433"
    volumes:
      - ./volumes/laywer.data.myssql:/var/opt/mssql
    networks:
      - backend

  lawyer.api.clients.webapi:
    image: lawyer.api.clients.webapi
    build:
      context: ../lawyer.api.clients/lawyer.api.clients.webapi
      dockerfile: ../lawyer.api.clients/lawyer.api.clients.webapi/Dockerfile
    ports:
      - 8080:8080
networks:
  backend:
    