services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: lawyer.data.mssql
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=lawyer.data.mssql.data001
    ports:
      - "1433:1433"
    volumes:
      - ./volumes/lawyer.data.myssql:/var/opt/mssql
    networks:
      - backend
  
  shared.webapi:
    image: lawyer.api.shared.webapi
    container_name: lawyer.api.shared.webapi
    build:
      context: ../lawyer.api.shared
      dockerfile: ./lawyer.api.shared.webapi/Dockerfile
    ports:
      - "8079:8080"
    networks:
      - backend
        
  auth.webapi:
    image: lawyer.api.auth.webapi
    container_name: lawyer.api.auth.webapi
    build:
      context: ../lawyer.api.auth
      dockerfile: ./lawyer.api.auth.webapi/Dockerfile
    ports:
      - "8080:8080"
    networks:
      - backend

  clients.webapi:
    image: lawyer.api.clients.webapi
    container_name: lawyer.api.clients.webapi
    build:
      context: ../lawyer.api.clients
      dockerfile: ./lawyer.api.clients.webapi/Dockerfile
    ports:
      - "8081:8080"
    networks:
      - backend
  
  laywers.webapi:
    image: lawyer.api.layers.webapi
    container_name: lawyer.api.lawyers.webapi
    build:
      context: ../lawyer.api.lawyers
      dockerfile: ./lawyer.api.lawyers.webapi/Dockerfile
    ports:
      - "8082:8080"
    networks:
      - backend

networks:
  backend:
    